### ISSUE TITLE
Broken when installing from setup.py

### ISSUE THREAD

**Issue by FFY00** [gaborbernat/sphinx-argparse-cli#4]
**Describe the bug**
When I install via `setup.py`, `version.py` does not seem to be generated.

**To Reproduce**
1. Download the latest release tarball
2. python setup.py install
3. Try to use the extension

```
Original exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/registry.py", line 417, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sphinx_argparse_cli/__init__.py", line 5, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'sphinx_argparse_cli.version'


Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/registry.py", line 417, in load_extension
    mod = import_module(extname)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/sphinx_argparse_cli/__init__.py", line 5, in <module>
    from .version import __version__
ModuleNotFoundError: No module named 'sphinx_argparse_cli.version'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 402, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.9/site-packages/sphinx/registry.py", line 420, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_argparse_cli (exception: No module named 'sphinx_argparse_cli.version')

Extension error:
Could not import extension sphinx_argparse_cli (exception: No module named 'sphinx_argparse_cli.version')
```

**Expected behavior**
Building via PEP 517 and via `setup.py` should both work.

**Environment (please complete the following information):**
 - Operating System and Version: Arch Linux

**Additional context**
I am packaging this project for Arch Linux.

**Comment by gaborbernat** [comment]
Have you provisioned the build dependencies within the python you're invoking?

**Comment by FFY00** [comment]
Yes.

**Comment by gaborbernat** [comment]
I wonder why is sphinx being invoked during the build (see registry).

**Comment by FFY00** [comment]
That output is for when you *try to use* the extension, it is not running during the build.

**Comment by FFY00** [comment]
The build succeeds, it just doesn't include the version module.

**Comment by FFY00** [comment]
Seems like `toml` was missing and setuptools-scm wasn't reading `pyproject.toml` because of that. Sorry.
